name: grpc_rocket
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  awesome_dialog: ^2.2.1
  file_picker: ^4.5.1
  provider: ^6.0.2
  bitsdojo_window: ^0.1.1+1
  dropdown_button2: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
